container:
  name: primary
  port: 5432
fullnameOverride: ""
image: registry.access.redhat.com/rhscl/postgresql-10-rhel7
imagePullSecrets: []
name: primary
nameOverride: ""
podSecurityContext: {}
pv:
  storage: 2Gi
pvc:
  name: primary-pvc
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
