apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-chart.fullname" . }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{.Values.container.port}}
      targetPort: {{.Values.container.port}}
      name: postgres
  selector:
    {{- include "postgres-chart.selectorLabels" . | nindent 4 }}
